spring:
  data:
    mongodb:
#      uri: mongodb://mongo:mongo@3.34.1.151:27018
      authentication-database: admin
      database: location
      uri: mongodb://localhost:27018
#      host: 3.34.1.151
#      port: 27018
#      username: mongo
#      password: mongo

  application:
    name: landmark-service

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
