spring:
  data:
    mongodb:
      authentication-database: admin
      database: location
      uri: mongodb://mongo:mongo@{host}:{port}
#      host: 00.000.000.000
#      port: 27017
#      username: mongo
#      password: mongo

  application:
    name: landmark-service

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
