spring:
  data:
    mongodb:
      host: 3.34.1.151
      port: 27018
      authentication-database: admin
      username: mongo
      password: mongo
      database: crawling
#      uri: mongodb://mongo:mongo@3.34.1.151:27018/admin

